### ISSUE TITLE
Fix responses

### ISSUE THREAD

**Issue by daniamcode** [alexmoleiro/sitechecker#9]
About some responses which look wrong

**Comment by daniamcode** [comment]
There are some issues with:
- glovo.es (responding a 408)
- mingle2.com (responding a 400)
- "non existant domain" case is not considered apart

**Comment by alexmoleiro** [comment]
Non-existent domain returns 404
SSL issue returns with 495 (https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)
